# Generated by Django 3.2 on 2021-04-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JVDjangoDBModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_status', models.IntegerField(default=1)),
                ('enabled_player', models.IntegerField(default=0)),
                ('strategy', models.IntegerField(default=0)),
                ('move_order', models.IntegerField(default=0)),
                ('strategy_way', models.IntegerField(default=0)),
                ('p11', models.IntegerField(default=0)),
                ('p12', models.IntegerField(default=0)),
                ('p13', models.IntegerField(default=0)),
                ('p21', models.IntegerField(default=0)),
                ('p22', models.IntegerField(default=0)),
                ('p23', models.IntegerField(default=0)),
                ('p31', models.IntegerField(default=0)),
                ('p32', models.IntegerField(default=0)),
                ('p33', models.IntegerField(default=0)),
            ],
        ),
    ]
